/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tools_mcode_disasm_Mcode */

#ifndef _Included_com_tools_mcode_disasm_Mcode
#define _Included_com_tools_mcode_disasm_Mcode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tools_mcode_disasm_Mcode
 * Method:    disassemble
 * Signature: ([CIJJI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tools_mcode_disasm_Mcode_disassemble
  (JNIEnv *, jobject, jcharArray, jint, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
